# Author: Dr. Andrew Scott
# Version: SP2017
# Description: A driver for the supa loto game
# DO NOT EDIT THIS FILE>
import random
import game_logic

# The maximum number permitted in this game
MAX_NO = 50
# The amount of numbers on a ticket.
NUMS_PER_TICKET = 6

DRAWS = 16


def game():
    """Play the fame of supa loto"""

    # make the ticket
    ticket = game_logic.generate_ticket()

    smallest = game_logic.smallest(ticket)

    # Display the ticket
    game_logic.display_ticket(ticket)

    # Check of the numbers
    print("\n==Numbers Drawn==")
    for n in range(DRAWS):
        rnd = random.randint(1, MAX_NO)
        print("[", rnd, sep="", end="]")
        game_logic.check_off(ticket, rnd)
        # Cause a new line
        print("")

    # Display the ticket with values checked off
    game_logic.display_ticket(ticket)

    # Deduce the prize if any
    prize = game_logic.wins(ticket)

    # Powerball bonus
    prize += game_logic.powerball(ticket, smallest)

    # Announce prize amount
    if prize > 0:
        print("You  won:", prize)
    else:
        print("Sorry no win")


def main():
    """Will run a game"""
    game()


# Will run the program if the user runs this code directly.
if __name__ == "__main__":
    main()
